accounts = ['_BRUBECK_', '3diy', 'AdvisorBooks', 'AgwiolNatural_pl', 'Allvita', 'animalsdog', 'Anixol_pl',
            'art-fotografia', 'Auto-od-A-do-Z', 'AUTO-WALDI1', 'bajkowypokoik_pl', 'bakaleo_pl', 'BeardMan_pl',
            'bimber_hobby', 'biotina_pl', 'bodykids', 'Clamoty-Shop', 'classic-bag', 'dawpol-bhppl', 'DELI_ADVANT',
            'dobre-pufy', 'dtu24-pl', 'duze-pufy', 'dwm-market', 'E-PHARM', 'ecoGryzaki', 'Ecomi-screen', 'Eleks728',
            'EvaMingeDesign', 'fajnydom_net', 'FlexWeed', 'FSOPAK', 'g-tzong', 'Glasmark-Allegro', 'Graw-tech',
            'grzejnikimc', 'gwalento', 'hamono_pl', 'handlowiec-rs-pl', 'handy-art_pl', 'Hitowezabawki', 'HSBB',
            'hurtowniabaseny', 'INNMARK', 'innovofood', 'irbis_style', 'italhouse', 'jurek1438', 'JustbuyShopGsm',
            'kawiarzsa', 'Kaysershop', 'kbarth_pl', 'KoktajleWarzywne', 'konkret_energy', 'KoomputeryPL', 'LIGPOLL',
            'livolopomorze', 'LOGOSTORE', 'lolas123', 'looveplants', 'M1985K', 'Maddi_pl', 'mag-bud-brodnica',
            'MAGBAFASHION', 'marketOK', 'Martellaspzoo', 'meble4m', 'mebletap-', 'MetalicznyPluton', 'Mikronatura',
            'miloscpartyshop', 'misumi24', 'mkk09', 'MOBIHELP', 'ModnaTySuperCeny', 'montre_bijoux', 'MOTO-ML',
            'MS-Instalacje', 'Najtaniej_w_EU', 'namioty-handlowe', 'nefryt-allegro', 'nefryt-srebro', 'NeuroNatural',
            'NEUTREA', 'OMGsklep', 'papaya_shop', 'Parts-store', 'PATIKA_SHOP', 'PhoneLove', 'PoButki',
            'polskieolejeCBD', 'PremiumHemp', 'Promo-Tech', 'protect-mobile', 'PryzmatMedia', 'pufy-pilki', 'QuickSub',
            'Raj_Nasion', 'Raj_Ogrodnika', 'ratownictwolife', 'red-arena', 'redil_', 'RODZINKOWO_PL',
            'rolety-moskitery', 'RosalieSklep', 'sacpuf', 'sandow_com_pl', 'Sandow_EU', 'securitycover', 'Seltrade',
            'sendobry', 'sklep-miszmasz', 'slawka_mad', 'SmA_Gatta', 'SmA-Babyliss', 'SPEC-KABLE', 'starhousegames',
            'StrefaMedyka', 'Stylowy__dom', 'Swiat-Juniora', 'TEXTYLIA_DOMOWE', 'tmcgalanteria', 'TOP_FIT', 'TopkKable',
            'torebkadamska_pl', 'twoja_przestrzen', 'UrbanCity', 'veltini', 'veltini-lazienka', 'westerness',
            'WIESZAKI_KROTON', 'woodroom', 'www_rufcio_pl', 'wwwkoomputerypl', 'yego-pl', 'yo-yos', 'Zapachy24h',
            'zetzoo_pl']
